### PR TITLE
Add search and search_all attributes

### PR DESCRIPTION
**Pull request by capjamesg**
# Description

This PR introduces two new methods:

- `search`: Returns the search results for a dataset search query.
- `search_all`: Returns a generator that yields pages of search results. 

## Type of change

Please delete options that are not relevant.

-   [X] New feature (non-breaking change which adds functionality)

## How has this change been tested, please provide a testcase or example of how you tested the change?

You can test this feature using the following code:

```
import roboflow

roboflow.login()

rf = roboflow.Roboflow()

# List all projects for your workspace
workspace = rf.workspace()

project = rf.project("mug-detector-23eqf")

# List all versions of a specific project
print(project.search(
    prompt="mug"
))

records = []

for page in project.search_all(
    prompt="mug"
):
    records.extend(page)

print(len(records))
```

You will need to specify your own dataset ID.

## Any specific deployment considerations

N/A

## Docs

I will update our quickstart docs on Gitbook once we release this feature.

### CODE REVIEW

**Review by Jacobsolawetz — APPROVED** [review]
Nice!

**Comment by Jacobsolawetz** [comment]
Be sure to `make style`

**Comment by capjamesg** [comment]
Done!

**Comment by capjamesg** [comment]
Let me know when you get the chance to release this in the pip package!

**Pull request merged**
