### PR TITLE
Added an environment variable to silence TQDM output

### PR DESCRIPTION
**Pull request by bigbitbus**
# Description

Add the option to quieten TQDM messages.

Set the environment variable TQDM_DISABLE=1 if you don't want the download/unzipping  progress-bars

## Type of change

Please delete options that are not relevant.

-   [X] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

## How has this change been tested, please provide a testcase or example of how you tested the change?

Testing in progress...will update here

## Any specific deployment considerations

For example, documentation changes, usability, usage/costs, secrets, etc.

## Docs

-   [ ] Docs updated? What were the changes:

### CODE REVIEW

**Comment by capjamesg** [comment]
@bigbitbus Let me know when this is ready for a review.

**Comment by bigbitbus** [comment]
> @bigbitbus Let me know when this is ready for a review.

Thanks, I'll fix it and ping you

**Comment by bigbitbus** [comment]
@capjamesg ready for review!

**Review by capjamesg — APPROVED** [review]
Looks good to me!

**Pull request merged**
