### PR TITLE
fix: 🐛 collab deps conflict fix

### PR DESCRIPTION
**Pull request by onuralpszr**
### Description

Google collab has more recent version of packages and current versioning causing issue when you install it. This should install higher. 

List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

-   [X] Bug fix (non-breaking change which fixes an issue)

Current Result

image

Fixed Result

image

### CODE REVIEW

**Comment by onuralpszr** [comment]
@capjamesg  after merge a quick minor release should fix the problem as well.

**Comment by capjamesg** [comment]
@paulguerrie Are there any concerns associated with removing the pinned version numbers and using the `>=` syntax?

**Comment by paulguerrie** [comment]
> @paulguerrie Are there any concerns associated with removing the pinned version numbers and using the `>=` syntax?

It might be worth adding a `<` for the next major revision. For example `dependancy>=4.5.1,<5.0.0` to avoid breaking changes, but not totally necessary.

**Comment by onuralpszr** [comment]
> > @paulguerrie Are there any concerns associated with removing the pinned version numbers and using the `>=` syntax?
> 
> It might be worth adding a `<` for the next major revision. For example `dependancy>=4.5.1,<5.0.0` to avoid breaking changes, but not totally necessary. 

Or we merge this in short term and I switch project  new toml for more controllable and add test for certain cases (just need login infos as secret so can do actually tests and  we can actually know in cases of breaking change until then we keep update as well

**Comment by capjamesg** [comment]
Thank you for your contribution! Could you submit a PR that uses a `pyproject.toml` file and then we can revisit this issue? It would be great if the `pyproject.toml` file don't cause a user to upgrade past a new major version as per @paulguerrie's comment earlier. I am going to close this PR for now and we can follow up should you be interested in submitting a `pyproject.toml` PR.

**Pull request closed without merging**
